apiVersion: apps/v1
kind: Deployment
metadata:
  name: omke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omke
  template:
    metadata:
      labels:
        app: omke
    spec:
      containers:
      - image: okteto.dev/omke:latest
        name: omke
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3a3f1a72-73b8-41fd-b211-3ec10f6dd670"
        - name: Vless_Path
          value: "/3a3f1a72-73b8-41fd-b211-3ec10f6dd670"
        - name: Vmess_UUID
          value: "b033af50-a9e1-46ee-b6a2-8af9e9b4ebfd"
        - name: Vmess_Path
          value: "/b033af50-a9e1-46ee-b6a2-8af9e9b4ebfd"
        - name: Share_Path
          value: "/v2link"
